# Clippy configuration for Phobos
cognitive-complexity-threshold = 30
type-complexity-threshold = 500
too-many-arguments-threshold = 8
too-many-lines-threshold = 200
array-size-threshold = 512000
vec-box-size-threshold = 4096
