# Phobos Port Scanner Configuration
target = "127.0.0.1"
ports = [22, 80, 443, 8080, 8443, 3389, 5432, 3306, 1433, 5000, 5001, 8000, 8001, 9000]
technique = "Connect"
threads = 100
timeout = 3000
rate_limit = 10000000
timing_template = 3
realtime_notifications = true
notification_color = "orange"
adaptive_learning = true
min_response_time = 50
max_response_time = 3000