# Cargo Deny Configuration for Phobos
# https://embarkstudios.github.io/cargo-deny/

# Note: Running these checks:
# cargo install cargo-deny
# cargo deny check

[advisories]
# Security vulnerability database
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
    # Add advisory IDs to ignore here if needed
    # "RUSTSEC-2020-0001",
]

[licenses]
# License checking
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Zlib",
    "0BSD",
    "BSL-1.0",
]
deny = [
    "GPL-1.0",
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
copyleft = "warn"
allow-osi-fsf-free = "both"
default = "deny"
confidence-threshold = 0.8

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[licenses.private]
ignore = false
registries = []

[bans]
# Banned crates
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

skip = [
    # Skip version checks for common duplicates
    { name = "windows-sys", version = "*" },
    { name = "windows_x86_64_msvc", version = "*" },
    { name = "windows_x86_64_gnu", version = "*" },
]

skip-tree = [
    # Skip entire dependency trees if needed
]

# Specific crate bans
deny = [
    # Add crates to ban here
    # { name = "unsafe-crate", version = "*" },
]

[sources]
# Source repository configuration
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
# Allow all crates from these GitHub orgs
github = ["ibrahmsql"]
